config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :schools do
    resources :grades do
      resources :students
    end 
  end
  authenticated :user do
    root 'schools#index', as: "authenticated_root"
  end
  root 'schools#welcome'
  get '*path' => redirect('/')

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :schools
	has_many :distances
end

app/models/distance.rb
class Distance < ActiveRecord::Base
	 belongs_to :city
	 has_many :schools
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	belongs_to :user
	belongs_to :school
	has_many :students
	

end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :grades
	belongs_to :city
	belongs_to :distance
	validates_presence_of :name, :distance_id, :city_id

	def self.search(school)
		if school
			where(["name LIKE ?", "%#{school}%"])
		else
			all
		end
	end

end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :grade
	validates_presence_of :number, :height, :weight
	validates_numericality_of :height, :weight, :numericality =>{greater_than: 0 }
	validates :number, presence: true, length: {maximum: 8}, numericality: true
	validates :name, presence: true, length: {maximum: 50}, format: {:with => /\A[a-z+ .]+\z/i }

	def bmi_value
		self.update(bmi: (weight / (height/100)**2).round(2))
	end

	


end	
# student.update(bmi: (@student.weight / (@student.height/100)**2).round(2))

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :grades
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show, :welcome]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password,
    :password_confirmation,
    :current_password, name)}
  end

end

app/controllers/grades_controller.rb
class GradesController < AdminController
	before_action :find_school
	before_action :find_grade, except: [:new, :create]


	def show
		@students = @grade.students
	end

	def new
		@grade = @school.grades.new
	end

	def create
		@grade = @school.grades.build(grade_params)
		if @grade.save
			@grade.update(user_id: current_user.id)
			flash[:success] = "Created a new grade successfully."
			redirect_to school_grade_path(@school, @grade)
		else
			render :new
		end

	end

	def edit
		
	end

	def update
		if @grade.update(grade_params)
			flash[:success] = "Updated your grade successfully."
			redirect_to school_grade_path(@school, @grade)
		else
			render :edit
		end
	end

	def destroy
		
	end

private

	def find_school
		@school = School.find(params[:school_id])
	end

	def find_grade
		@grade = @school.grades.find(params[:id])
	end

	def grade_params
		params.require(:grade).permit(:name, :user_id, :school_id)
	end




end

app/controllers/schools_controller.rb
class SchoolsController < AdminController

	before_action :find_school, only: [:edit, :update, :show, :destroy]

	def index
		if params[:city].blank?
			@schools = School.search(params[:search])
		else
			@city_id = City.find_by(name: params[:city]).id
			@schools = School.where(city_id: @city_id).order("created_on DESC")
		end
	end

	def new
		@school = School.new
	end

	def create
		@school = School.new(school_params)
		if @school.save
			flash[:success] = "Added New School Successfully."
			redirect_to @school
		else
			render :new
		end
	end

	def show
		@grades = @school.grades
	end

	def edit
		
	end

	def update
		if @school.update(school_params)
			flash[:success] = "Update School Successfully."
			redirect_to @school
		else
			render :edit
		end
	end

	def destroy
		
	end

	private

	def find_school
		@school = School.find(params[:id])
	end

	def school_params
		params.require(:school).permit(:name, :city_id, :distance_id)
	end

end

app/controllers/students_controller.rb
class StudentsController < AdminController

	before_action :find_school
	before_action :find_grade
	before_action :find_student, except: [:new, :create]



	def new
		@student = @grade.students.build
	end

	def create
		@student = @grade.students.build(student_params)
		if @student.save
			@student.bmi_value
			flash[:success] = "Congratulation! New member in your class."
			redirect_to school_grade_path(@school, @grade)
		else
			render :new
		end
	end

	def edit
		
	end

	def update
		if @student.update(student_params)
			@student.bmi_value
			flash[:success] = "Updated class member successfully."
			redirect_to school_grade_path(@school, @grade)
		else
			render :edit
		end
	end

	def destroy
		@student.destroy
		redirect_to :back
	end

private
	def find_school
		@school = School.find(params[:school_id])	
	end

	def find_grade
		@grade = @school.grades.find(params[:grade_id])
	end

	def find_student
		@student = @grade.students.find(params[:id])
	end

	def student_params
		params.require(:student).permit(:number, :name, :birth,
																		:height, :weight, :gender, :bmi)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

  def serial_no(school, i=0)
    school.created_on.strftime("%Y%m%d") +  sprintf('%03d',i+1).to_s
  end
	
  def name_capitalize(name)
    name_to_a = name.split(" ")
    capital = name_to_a.collect {|i| i.capitalize }
    tos = capital.join(" ")
    tos
  end

end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2016 Design by Bill
  </p>
</footer>

app/views/common/_navbar.html.erb
<div class="container-fluid">
    
  <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="/" style="color: #B8C129">BMI for World</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to("School List", root_path) %>
          </li>
        </ul>
        
        <%= form_tag schools_path, method: :get,class: "navbar-form navbar-left"  do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search school" %>
          <%= submit_tag "Search" %>
        <% end %>

        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hi, <%= current_user.name || current_user.email %>
               <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
              </ul>
            </li>
      
        </ul>
      </div><!-- /.navbar-collapse -->
    <!-- /.container-fluid -->
  </nav>
</div>

app/views/common/_navber.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">BMI for World</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("School List", root_path) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in %>
          <li><%= link_to("登入", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi, <%= current_user.email unless current_user.name.nil? %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/grades/_form.html.erb
<%= form_for [@school, @grade] do |f| %>

	<div id="error_explanation">
		<% if @grade.errors.any? %>
			<h2><%= pluralize(@grade.errors.count, "error") %> prevented this from saving:</h2>
			<ul>
				<% @grade.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
			<% end %>
	</div>

	<br>

	<div class="field">
		<%= f.label :name, "Class Name"  %> <br>
		<%= f.text_field :name, placeholder: "Ex: 3年2班" %> 
	</div>
	<br>

		<%= f.submit class: "button" %>

<% end %>

app/views/grades/edit.html.erb
<div id="form">
	<h1><%= @school.name %></h1>
	<h3>Edit Class</h3> 
	<hr>

	<%= render 'form' %>
	<hr>

	<%= link_to "Back", @school, class: "back"  %>
</div>

app/views/grades/new.html.erb
	
<div id="form">
	<h1><%= @school.name %></h1>
	<h3>New Class</h3> 
	<hr>

	<%= render 'form' %>
	<hr>

	<%= link_to "Back", @school, class: "back"  %>
</div>

app/views/grades/show.html.erb
<div id="grade_show">

	<h2><%= @grade.school.name %>-<%= @grade.name %></h2> 
		
	<% if user_signed_in? && @grade.user == current_user %>
	<%= link_to edit_school_grade_path(@school,@grade), class: "icon"  do %>
		<i class="fa fa-pencil-square-o fa-lg"></i>
	<% end %>
	<hr>
	<%= link_to new_school_grade_student_path(@school,@grade), class: "icon" do %>
		<i class="fa fa-plus-circle fa-lg"></i>
		<% end %>
	<% end %>

		<table class="table table-hover table-bordered">
		<thead>
			<tr>
				<th>Student Id</th>
				<th>Student Name</th>
				<th>Birthday</th>
				<th>Gender</th>
				<th>Height</th>
				<th>Weight</th>
				<th>BMI</th>
				<th>Options</th>
			</tr>
		</thead>

		<tbody>
			<% @students.each do |student| %>
				<tr>
					<td><%= student.number %></td>
					<td><%= name_capitalize(student.name) %></td>
					<td><%= student.birth %></td>
					<td><%= student.gender %></td>
					<td><%= student.height %> cm</td>
					<td><%= student.weight %> kg</td>
					<td><%= student.bmi %></td>
					<td class="options">
					<% if user_signed_in? && @grade.user == current_user %>
						<%= link_to edit_school_grade_student_path(@school,@grade, student) do %>
							<i class="fa fa-wrench"></i>
						<% end %>
						<%= link_to school_grade_student_path(@school,@grade,student), method: :delete,
							data: {confirm: "Are you sure?"} do  %>
							<i class="fa fa-times"></i>
						<% end %>
					<% else %>
						<i class="fa fa-wrench", style="opacity: 0.4"></i>
						<i class="fa fa-times" , style="opacity: 0.4"></i>
					<% end %>
					</td>
				</tr>
			<% end %>
		</tbody>

	</table>
	

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BmiForWorld</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700,600,800,500' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
		<%= render 'common/navbar' %>
		<%= notice_message %>
		<%= yield %>
		<% else %>
	<%= yield %>
	<% end %>
<%= render 'common/footer' %>
</body>
</html>

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>

	<div id="error_explanation">
		<% if @school.errors.any? %>
			<h2><%= pluralize(@school.errors.count, "error") %> prevented this from saving:</h2>
			<ul>
				<% @school.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
			<% end %>
	</div>

	<div class="select_city">
		<%= f.label :city_id, "City" %>  <br>
		<%= f.collection_select :city_id, City.all, :id, :name, include_blank: true %> 
	</div>  

	<br>

	<div class="select_country">
		<%= f.label :distance_id, "Distance" %> <br>
		<%= f.grouped_collection_select :distance_id, City.all, :distances, :name, :id, :name, include_blank: true %>  
	</div>
	<br>
	<div class="field">
		<%= f.label :name, "School Name"  %> <br>
		<%= f.text_field :name, placeholder: "Ex: 士林國小" %> 
	</div>
	<br>

		<%= f.submit class: "button" %>

<% end %>

app/views/schools/edit.html.erb
<div id="form">
	<h2>Edit School</h2> 
	<hr>

	<%= render 'form' %>
	<hr>

	<%= link_to "Back", root_path, class: "back"  %>
</div>

app/views/schools/index.html.erb
<div class="container school">
	<div class="city">
		<ul class="nav nav-pills">
			<li><%= link_to "All School", root_path  %></li>
			<% City.all.each do |city| %>

			<li><%= link_to city.name, schools_path(city: city.name)  %></li>
			<% end %>
		</ul>
	</div>
	<div id="table" class="clearfix">		
		<h2>School List</h2>  
		<% if user_signed_in? %>
			<%= link_to "New School", new_school_path  %>
		<% end %>
		<hr>
		<table class="table table-hover table-bordered">
			<thead>
				<tr>
					<th>Created Id</th>
					<th>City</th>
					<th>Distance</th>
					<th>School Name</th>
				</tr>
			</thead>

			<tbody>
				<% @schools.each_with_index do |school, i| %>
					<tr>
						<td><%= serial_no(school,i) %></td>
						<td><%= school.city.name %></td>
						<td><%= school.distance.name %></td>
						<td><%= link_to school.name, school %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/schools/new.html.erb
<div id="form">
	<h2>New School</h2> 
	<hr>

	<%= render 'form' %>
	<hr>

	<%= link_to "Back", root_path, class: "back"  %>
</div>

app/views/schools/show.html.erb
<div id="show">
	<h2><%= @school.city.name + @school.distance.name + @school.name %></h2>  
	
	<% if user_signed_in? %>
		<%= link_to edit_school_path(@school), class: "icon"  do %>
			<i class="fa fa-pencil-square-o fa-lg"></i>
		<% end %>
	
		<%= link_to new_school_grade_path(@school), class: "icon" do %>
			<i class="fa fa-plus-circle fa-lg"></i>	
		<% end %>
	<% end %>
	
	<hr>
			


	<div class="grade_list">
	 <ul>
	 	<% @grades.each do |grade| %>

			<li class="cf"><h4><%= link_to grade.name, school_grade_path(@school, grade) %> |</h4> </li>
		<% end %>
	 </ul>
	</div>


</div>

app/views/schools/welcome.html.erb
<div class="welcome">
	<nav class="navbar navbar-default" role="navigation"> 
		 <a class="navbar-brand" href="/" style="color: #B8C129">BMI for World</a>
	      <ul class="nav navbar-nav navbar-right" style="padding-right: 1rem;">      
         	<li><%= link_to "Sign Up", new_user_registration_path %></li>
         	<li><%= link_to "Sign In", new_user_session_path  %></li>   
      </ul>
	</nav>

	
	<div class="bmi_info container">
		<h2>What is BMI?</h2>
		<p>
			The body mass index (or BMI) is a measure which shows whether people have the right weight for their height. <br> The World Health Organisation (WHO), governments and health workers use it. It is also sometimes called the Quetelet Index.
		</p>
	</div>
</div>
	
<div class="why container-fluid">
	<h2>Let's Go record your BMI</h2>
	<p>
			Make you handle all the student's health!
	</p>
	<p>Be a health Men and Women</p>
			<br>
			<img src="assets/bmi.jpg" alt="bmi" class="img-circle" width="400" height="200">
			<br>
			<p><%= link_to "Click me to Sign Up", new_user_registration_path  %></p>
	</div>

app/views/students/_form.html.erb
<%= form_for [@school, @grade, @student] do |f| %>

<div id="error_explanation">
	<% if @student.errors.any? %>
		<h2><%= pluralize(@student.errors.count, "error") %> prevented this from saving:</h2>
		<ul>
			<% @student.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		<% end %>
</div>

<br>
<div class="field">
	<%= f.label :number, "Student ID"  %> <br>
	<%= f.number_field :number, :max => 99999999 %> 
</div>

<div class="field">
	<%= f.label :name, "Student's Name"  %> <br>
	<%= f.text_field :name, placeholder: "English name, ex: Bill Hung" %> 
</div>

<div class="field">
	<%= f.label :gender, "Gender"  %> <br>
	<%= f.select :gender, options_for_select([ "Male", "Female" ], "Male") %>
</div>

<div class="f">
	<%= f.label :birth, "Birthday"  %> <br>
	<%= f.date_select :birth, start_year: Date.today.year - 70, end_year: Date.today.year %> 
</div>  <br>

<div class="field">
	<%= f.label :height, "Height"  %> <br>
	<%= f.number_field :height, :step => 0.1, :max => 300 %> <em>cm</em>
</div>

<div class="field">
	<%= f.label :weight, "Weight"  %> <br>
	<%= f.number_field :weight, :step => 0.1, :max => 200 %> <em>kg</em>
</div>



<br>

	<%= f.submit class: "button" %>
	

<% end %>

app/views/students/edit.html.erb
<div id="stu_form">
	<h1><%= @grade.name %></h1>
	<h2>Edit Class Member </h2> 
	<hr>

	<%= render 'form' %>
	<hr>

	<%= link_to "Back", school_grade_path(@school, @grade), class: "back"  %>
</div>

app/views/students/new.html.erb
<div id="stu_form">
	<h1><%= @grade.name %></h1>
	<hr>

	<%= render 'form' %>
	<hr>

	<%= link_to "Back", school_grade_path(@school, @grade), class: "back"  %>
</div>